module.exports = {
	ContactSchema: require('./Contact'),
	UserSchema: require('./DiscordUser'),
	GiveawaySchema: require('./Giveaway'),
	GlobalBanSchema: require('./GlobalBan'),
	GuildSchema: require('./GuildSettings'),
	RankSchema: require('./Level'),
	PartnerSchema: require('./PartnerShip'),
	PlaylistSchema: require('./Playlist'),
	PremiumSchema: require('./Premium'),
	ReactionRoleSchema: require('./ReactionRole'),
	StaffApplicationSchema: require('./StaffApplication'),
	timeEventSchema: require('./TimedEvents'),
	WarningSchema: require('./Warning'),
};
